# .project metadata for KubeVela
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "kubevela"
name: "KubeVela"
description: "Make shipping applications more enjoyable"
type: "project"
slack_channels:
  - name: "#kubevela"
    link: "https://cloud-native.slack.com/archives/C01BLQ3HTJA"
    primary: true

maturity_log:
  - phase: "sandbox"
    date: "2021-06-22T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/680"

  - phase: "incubating"
    date: "2023-02-27T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/890"

repositories:
  - url: "https://github.com/kubevela/kubevela"
    primary: true
    # tags: [core, sig-apps] # Optional

website: "https://kubevela.io"

artwork: "https://cncf-icons.com/artwork/projects/kubevela/icon/color/kubevela-icon-color.svg"

adopters:
  path: "https://github.com/kubevela/community/blob/main/ADOPTERS.md"

package_managers:
  docker:
    - oamdev/vela-core
    - oamdev/vela-cli
  helm: "https://kubevela.github.io/charts"

social:
  twitter: "https://twitter.com/oam_dev"

security:
  policy:
    path: "https://github.com/kubevela/kubevela/blob/master/SECURITY.md"
  contact:
    advisory_url: "https://github.com/kubevela/kubevela/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/kubevela/kubevela/blob/master/CONTRIBUTING.md"
  governance_doc:
    path: "https://github.com/kubevela/kubevela/blob/master/GOVERNANCE.md"
  code_of_conduct:
    path: "https://github.com/kubevela/kubevela/blob/master/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/kubevela/kubevela/blob/master/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kubevela/kubevela/blob/master/README.md"

landscape:
  category: "App Definition and Development"
  subcategory: "Application Definition & Image Build"
# CLOMonitor Score: 87/100
# Documentation: 95 | License: 75 | Best Practices: 100 | Security: 88
